In [2]:
#Python Program to Find Sum of Natural Numbers Using Recursion.
def sum(n):
    if n<=1:
        return n
    else:
        return n + sum(n-1)
print("sum =",sum(16))    

sum = 136


In [3]:
#Python Program to Find Factorial of Number Using Recursion.
def fact(n):
    if n==0:
        return 1
    else:
        return n*fact(n-1)
print("Factorial =",fact(5))    

Factorial = 120


In [7]:
#Python Program to Add Two Matrices.
import numpy as np
m1=np.array([[5,9,4],[2,8,8]])
print("Matrix 1 =\n",m1)
m2=np.array([[9,9,1],[7,3,8]])
print("Matrix 2 =\n",m2)
m3=np.add(m1,m2)
print("Sum of matrix 1 and matrix 2 is\n",m3)

Matrix 1 =
 [[5 9 4]
 [2 8 8]]
Matrix 2 =
 [[9 9 1]
 [7 3 8]]
Sum of matrix 1 and matrix 2 is
 [[14 18  5]
 [ 9 11 16]]


In [10]:
#Python Program to Add Two Matrices using Nested List Comprehension.
x = [[5,9,4],
    [2,8,8]]
y = [[9,9,1],
    [7,3,8]]
result = [[x[i][j]+y[i][j] for j in range(len(x[0]))] for i in range(len(y))]
print("Sum of matrix x and matrix y is")
for r in result:
    print(r)

Sum of matrix x and matrix y is
[14, 18, 5]
[9, 11, 16]


In [13]:
#Python Program to Transpose a Matrix using Nested Loop.
x = [[5,9,4],
    [2,8,8],
    [3,3,3]]
print("Transpose is")
t= [[0,0,0],
    [0,0,0],
    [0,0,0]]
for i in range(len(x)):
    for j in range(len(x[0])):
        t[i][j]=x[j][i]
for r in t:
    print(r)

Transpose is
[5, 2, 3]
[9, 8, 3]
[4, 8, 3]


In [14]:
#Python Program to Transpose a Matrix using Nested List Comprehension.
x = [[5,9,4],
    [2,8,8],
    [3,3,3]]
print("Transpose is")
t=[[x[j][i] for j in range(len(x[0]))]for i in range(len(x))]
for r in t:
    print(r)

Transpose is
[5, 2, 3]
[9, 8, 3]
[4, 8, 3]


In [15]:
#Python Program to Check Whether a String is Palindrome or Not.
n=input("Enter a string: ")
m=n.lower()
if m[0:]==m[::-1]:
    print("It is a Palindrome")
else:
    print("It is not a Palindrome")

Enter a string: aIbohPhoBiA
It is a Palindrome


In [19]:
#Python Program to Remove Punctuations From a String.
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
string=input("Enter a String: ")
new=""
for i in string:
    if i not in punctuations:
        new=new+i
print(new)        

Enter a String: abc__d**&e
abcde
